version: "3.9"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --workers 2
      --timeout-keep-alive 5

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    command: >
      celery -A app.workers.celery_app worker
      --loglevel=info
      --concurrency=2
      --queues=high_priority,normal,low
      --max-tasks-per-child=50

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    command: >
      celery -A app.workers.celery_app beat
      --loglevel=info
      --scheduler redbeat.RedBeatScheduler

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://13.127.242.95:8000
      NODE_ENV: production

