import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base all models inherit from."""


class UUIDMixin:
    """Adds a UUID v4 primary key.

    Generated by Python before INSERT so the id is available before
    the session is flushed — useful for building relationships in memory.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Adds timezone-aware ``created_at`` and ``updated_at`` columns.

    ``updated_at`` is refreshed via SQLAlchemy's ``onupdate`` hook on
    every ORM-level UPDATE statement.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
