import uuid
from typing import Any, Optional

from fastapi import Depends, Request
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db, set_rls_context
from app.core.exceptions import AuthenticationError, AuthorizationError, NotFoundError
from app.core.logging import get_logger
from app.core.security import is_user_blocked, verify_access_token
from app.models.organization import Organization
from app.models.user import AccountType, User

logger = get_logger(__name__)

security = HTTPBearer(auto_error=False)

PLAN_HIERARCHY: dict[str, int] = {
    "free": 0,
    "smb": 1,
    "growth": 2,
    "ca_firm": 3,
    "admin": 99,
}


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------


async def get_db_session(
    db: AsyncSession = Depends(get_db),
) -> AsyncSession:
    """Pass-through dependency — returns the request-scoped AsyncSession."""
    return db


# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------


async def get_current_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security),
    db: AsyncSession = Depends(get_db),
) -> User:
    """Validate the Bearer JWT and return the authenticated User.

    Raises ``AuthenticationError`` (401) when the token is missing,
    invalid, expired, or the user account is inactive.
    """
    if credentials is None:
        raise AuthenticationError.token_invalid()

    payload = verify_access_token(credentials.credentials)

    result = await db.execute(
        select(User).where(User.id == uuid.UUID(payload.sub))
    )
    user = result.scalar_one_or_none()

    if user is None:
        raise AuthenticationError.token_invalid()

    if not user.is_active:
        raise AuthenticationError.invalid_credentials()

    if await is_user_blocked(str(user.id)):
        raise AuthenticationError(message="Account has been deleted.", code="AUTH_005")

    # Set PostgreSQL session variables so RLS policies can read them.
    await set_rls_context(db, user_id=str(user.id), org_id=payload.org_id)

    return user


async def get_current_org(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Organization:
    """Return the primary organisation that belongs to the current user."""
    result = await db.execute(
        select(Organization).where(Organization.owner_user_id == current_user.id)
    )
    org = result.scalar_one_or_none()
    if org is None:
        raise NotFoundError.organization(str(current_user.id))
    return org


# ---------------------------------------------------------------------------
# Authorisation
# ---------------------------------------------------------------------------


def require_plan(minimum_plan: str) -> Any:
    """Dependency factory — enforce a minimum subscription plan.

    Usage::

        @router.get("/export")
        async def export(org: Organization = Depends(require_plan("growth"))):
            ...
    """

    async def check_plan(
        org: Organization = Depends(get_current_org),
    ) -> Organization:
        user_level = PLAN_HIERARCHY.get(org.plan.value, 0)
        required_level = PLAN_HIERARCHY.get(minimum_plan, 0)
        if user_level < required_level:
            raise AuthorizationError.plan_upgrade_required(
                required_plan=minimum_plan,
                current_plan=org.plan.value,
            )
        return org

    return check_plan


async def require_admin(
    current_user: User = Depends(get_current_user),
) -> User:
    """Raise 403 unless the current user has account_type == admin."""
    if current_user.account_type != AccountType.admin:
        raise AuthorizationError.insufficient_permissions("admin")
    return current_user


# ---------------------------------------------------------------------------
# Request metadata helpers
# ---------------------------------------------------------------------------


def get_request_id(request: Request) -> str:
    """Return the request UUID generated by RequestLoggingMiddleware."""
    return getattr(request.state, "request_id", "")


def get_client_ip(request: Request) -> Optional[str]:
    """Return the real client IP, honouring X-Forwarded-For from Nginx."""
    forwarded_for = request.headers.get("X-Forwarded-For")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()
    if request.client:
        return request.client.host
    return None


def get_user_agent(request: Request) -> Optional[str]:
    """Return the User-Agent header value, or None if absent."""
    return request.headers.get("User-Agent")
