"""notice_share_token_and_new_types

Revision ID: 04d46a92062f
Revises: 9c04ba3da15c
Create Date: 2026-05-21 15:11:05.450696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d46a92062f'
down_revision: Union[str, None] = '9c04ba3da15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new enum values to notice_type (must run outside transaction)
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE notice_type ADD VALUE IF NOT EXISTS 'DRC_01A'")
        op.execute("ALTER TYPE notice_type ADD VALUE IF NOT EXISTS 'ASMT_10'")
        op.execute("ALTER TYPE notice_type ADD VALUE IF NOT EXISTS 'ASMT_11'")
        op.execute("ALTER TYPE notice_type ADD VALUE IF NOT EXISTS 'REG_03'")
        op.execute("ALTER TYPE notice_type ADD VALUE IF NOT EXISTS 'REG_17'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('draft_warnings', sa.JSON(), nullable=True))
    op.add_column('notices', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.add_column('notices', sa.Column('share_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_notices_share_token'), 'notices', ['share_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_share_token'), table_name='notices')
    op.drop_column('notices', 'share_token_expires_at')
    op.drop_column('notices', 'share_token')
    op.drop_column('notices', 'draft_warnings')
    # ### end Alembic commands ###
