"""ca_firm_white_label

Revision ID: 1a2f47f2680a
Revises: 04d46a92062f
Create Date: 2026-05-21 15:28:22.200345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2f47f2680a'
down_revision: Union[str, None] = '04d46a92062f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_firms',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=False),
    sa.Column('icai_firm_registration_number', sa.String(length=50), nullable=False),
    sa.Column('primary_ca_name', sa.String(length=255), nullable=False),
    sa.Column('icai_membership_number', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('white_label_subdomain', sa.String(length=63), nullable=True),
    sa.Column('logo_s3_key', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_clients', sa.Integer(), nullable=False),
    sa.Column('total_referral_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ca_firms_icai_firm_registration_number'), 'ca_firms', ['icai_firm_registration_number'], unique=True)
    op.create_index(op.f('ix_ca_firms_owner_user_id'), 'ca_firms', ['owner_user_id'], unique=True)
    op.create_index(op.f('ix_ca_firms_white_label_subdomain'), 'ca_firms', ['white_label_subdomain'], unique=True)
    op.create_table('ca_client_relationships',
    sa.Column('ca_firm_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'removed', name='ca_client_status'), nullable=False),
    sa.Column('referral_commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ca_firm_id'], ['ca_firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ca_firm_id', 'organization_id', name='uq_ca_firm_org')
    )
    op.create_index(op.f('ix_ca_client_relationships_ca_firm_id'), 'ca_client_relationships', ['ca_firm_id'], unique=False)
    op.create_index(op.f('ix_ca_client_relationships_organization_id'), 'ca_client_relationships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ca_client_relationships_status'), 'ca_client_relationships', ['status'], unique=False)
    op.create_table('referral_commissions',
    sa.Column('ca_firm_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'cancelled', name='referral_commission_status'), nullable=False),
    sa.Column('payout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ca_firm_id'], ['ca_firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_commissions_ca_firm_id'), 'referral_commissions', ['ca_firm_id'], unique=False)
    op.create_index('ix_referral_commissions_firm_status', 'referral_commissions', ['ca_firm_id', 'status'], unique=False)
    op.create_index(op.f('ix_referral_commissions_organization_id'), 'referral_commissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_referral_commissions_payment_id'), 'referral_commissions', ['payment_id'], unique=True)
    op.create_index(op.f('ix_referral_commissions_status'), 'referral_commissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_commissions_status'), table_name='referral_commissions')
    op.drop_index(op.f('ix_referral_commissions_payment_id'), table_name='referral_commissions')
    op.drop_index(op.f('ix_referral_commissions_organization_id'), table_name='referral_commissions')
    op.drop_index('ix_referral_commissions_firm_status', table_name='referral_commissions')
    op.drop_index(op.f('ix_referral_commissions_ca_firm_id'), table_name='referral_commissions')
    op.drop_table('referral_commissions')
    op.drop_index(op.f('ix_ca_client_relationships_status'), table_name='ca_client_relationships')
    op.drop_index(op.f('ix_ca_client_relationships_organization_id'), table_name='ca_client_relationships')
    op.drop_index(op.f('ix_ca_client_relationships_ca_firm_id'), table_name='ca_client_relationships')
    op.drop_table('ca_client_relationships')
    op.drop_index(op.f('ix_ca_firms_white_label_subdomain'), table_name='ca_firms')
    op.drop_index(op.f('ix_ca_firms_owner_user_id'), table_name='ca_firms')
    op.drop_index(op.f('ix_ca_firms_icai_firm_registration_number'), table_name='ca_firms')
    op.drop_table('ca_firms')
    # ### end Alembic commands ###
