"""add_preferences_share_token_final

Revision ID: 587e93e1b033
Revises: 7eff95805fd2
Create Date: 2026-05-21 20:08:03.122557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587e93e1b033'
down_revision: Union[str, None] = '7eff95805fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('whatsapp_deadline_reminders', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_scan_complete', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_mismatch_alerts', sa.Boolean(), nullable=False),
    sa.Column('email_scan_complete', sa.Boolean(), nullable=False),
    sa.Column('email_weekly_digest', sa.Boolean(), nullable=False),
    sa.Column('email_product_updates', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
