"""add_compliance_scores

Revision ID: 7eff95805fd2
Revises: 1a2f47f2680a
Create Date: 2026-05-21 16:43:25.230581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eff95805fd2'
down_revision: Union[str, None] = '1a2f47f2680a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_scores',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=3), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_scores_calculated_at'), 'compliance_scores', ['calculated_at'], unique=False)
    op.create_index('ix_compliance_scores_org_calculated', 'compliance_scores', ['organization_id', 'calculated_at'], unique=False)
    op.create_index(op.f('ix_compliance_scores_organization_id'), 'compliance_scores', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_scores_organization_id'), table_name='compliance_scores')
    op.drop_index('ix_compliance_scores_org_calculated', table_name='compliance_scores')
    op.drop_index(op.f('ix_compliance_scores_calculated_at'), table_name='compliance_scores')
    op.drop_table('compliance_scores')
    # ### end Alembic commands ###
