"""add_itc_tables

Revision ID: 9c04ba3da15c
Revises: cc6f538384d0
Create Date: 2026-05-21 14:05:33.268734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c04ba3da15c'
down_revision: Union[str, None] = 'cc6f538384d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itc_scans',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('scan_month', sa.String(length=7), nullable=False),
    sa.Column('gstr3b_s3_key', sa.String(length=500), nullable=False),
    sa.Column('gstr2b_s3_key', sa.String(length=500), nullable=False),
    sa.Column('total_invoices_checked', sa.Integer(), nullable=False),
    sa.Column('total_unclaimed_itc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_excess_claimed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_at_risk', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='itc_scan_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_itc_scans_org_month', 'itc_scans', ['organization_id', 'scan_month'], unique=False)
    op.create_index(op.f('ix_itc_scans_organization_id'), 'itc_scans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_itc_scans_status'), 'itc_scans', ['status'], unique=False)
    op.create_table('itc_issues',
    sa.Column('itc_scan_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.String(length=10), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('available_itc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('claimed_itc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['itc_scan_id'], ['itc_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itc_issues_itc_scan_id'), 'itc_issues', ['itc_scan_id'], unique=False)
    op.create_index('ix_itc_issues_scan_id', 'itc_issues', ['itc_scan_id'], unique=False)
    op.create_index('ix_itc_issues_scan_type', 'itc_issues', ['itc_scan_id', 'issue_type'], unique=False)
    op.create_index('ix_itc_issues_type', 'itc_issues', ['issue_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_itc_issues_type', table_name='itc_issues')
    op.drop_index('ix_itc_issues_scan_type', table_name='itc_issues')
    op.drop_index('ix_itc_issues_scan_id', table_name='itc_issues')
    op.drop_index(op.f('ix_itc_issues_itc_scan_id'), table_name='itc_issues')
    op.drop_table('itc_issues')
    op.drop_index(op.f('ix_itc_scans_status'), table_name='itc_scans')
    op.drop_index(op.f('ix_itc_scans_organization_id'), table_name='itc_scans')
    op.drop_index('ix_itc_scans_org_month', table_name='itc_scans')
    op.drop_table('itc_scans')
    # ### end Alembic commands ###
