"""initial_schema

Revision ID: cc6f538384d0
Revises: 
Create Date: 2026-05-20 15:25:45.802517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6f538384d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_org_created_at', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_audit_logs_user_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.Enum('smb', 'growth', 'ca_firm', 'admin', name='account_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_type'), 'users', ['account_type'], unique=False)
    op.create_index('ix_users_active_account_type', 'users', ['is_active', 'account_type'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('organizations',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('plan', sa.Enum('free', 'smb', 'growth', 'ca_firm', name='org_plan'), nullable=False),
    sa.Column('subscription_status', sa.Enum('active', 'cancelled', 'past_due', 'trialing', 'inactive', name='org_subscription_status'), nullable=False),
    sa.Column('invoice_limit', sa.Integer(), nullable=False),
    sa.Column('invoices_used_this_month', sa.Integer(), nullable=False),
    sa.Column('billing_cycle_start', sa.Date(), nullable=True),
    sa.Column('billing_cycle_end', sa.Date(), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_gstin'), 'organizations', ['gstin'], unique=True)
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_organizations_plan'), 'organizations', ['plan'], unique=False)
    op.create_index('ix_organizations_plan_sub_status', 'organizations', ['plan', 'subscription_status'], unique=False)
    op.create_index(op.f('ix_organizations_subscription_status'), 'organizations', ['subscription_status'], unique=False)
    op.create_table('notices',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('notice_number', sa.String(length=100), nullable=False),
    sa.Column('notice_type', sa.Enum('DRC_01', 'DRC_01C', 'DRC_07', 'DRC_10', 'other', name='notice_type'), nullable=False),
    sa.Column('demand_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_period', sa.String(length=20), nullable=True),
    sa.Column('response_due_date', sa.Date(), nullable=True),
    sa.Column('pdf_s3_key', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('draft_reply_text', sa.Text(), nullable=True),
    sa.Column('draft_status', sa.Enum('pending', 'generated', 'reviewed', 'approved', name='draft_status'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('icai_membership_number', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_draft_status'), 'notices', ['draft_status'], unique=False)
    op.create_index('ix_notices_org_draft_status', 'notices', ['organization_id', 'draft_status'], unique=False)
    op.create_index(op.f('ix_notices_organization_id'), 'notices', ['organization_id'], unique=False)
    op.create_table('scans',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('scan_month', sa.String(length=7), nullable=False),
    sa.Column('gstr1_s3_key', sa.String(length=500), nullable=False),
    sa.Column('gstr3b_s3_key', sa.String(length=500), nullable=False),
    sa.Column('pdf_s3_key', sa.String(length=500), nullable=True),
    sa.Column('total_invoices_scanned', sa.Integer(), nullable=False),
    sa.Column('total_mismatches', sa.Integer(), nullable=False),
    sa.Column('total_rupee_risk', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='scan_status'), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_is_paid'), 'scans', ['is_paid'], unique=False)
    op.create_index('ix_scans_org_month', 'scans', ['organization_id', 'scan_month'], unique=False)
    op.create_index('ix_scans_org_status', 'scans', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_scans_organization_id'), 'scans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('smb', 'growth', 'ca_firm', name='subscription_plan'), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'cancelled', 'past_due', 'paused', name='subscription_status'), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('mismatches',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('mismatch_type', sa.Enum('missing_in_3b', 'missing_in_1', 'value_mismatch', 'tax_mismatch', name='mismatch_type'), nullable=False),
    sa.Column('gstr1_taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gstr3b_taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gstr1_tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gstr3b_tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rupee_difference', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mismatches_mismatch_type'), 'mismatches', ['mismatch_type'], unique=False)
    op.create_index(op.f('ix_mismatches_scan_id'), 'mismatches', ['scan_id'], unique=False)
    op.create_index('ix_mismatches_scan_type', 'mismatches', ['scan_id', 'mismatch_type'], unique=False)
    op.create_table('payments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_type', sa.Enum('one_time_scan', 'subscription', name='payment_type'), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_index('ix_payments_org_status', 'payments', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index('ix_payments_org_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_mismatches_scan_type', table_name='mismatches')
    op.drop_index(op.f('ix_mismatches_scan_id'), table_name='mismatches')
    op.drop_index(op.f('ix_mismatches_mismatch_type'), table_name='mismatches')
    op.drop_table('mismatches')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_organization_id'), table_name='scans')
    op.drop_index('ix_scans_org_status', table_name='scans')
    op.drop_index('ix_scans_org_month', table_name='scans')
    op.drop_index(op.f('ix_scans_is_paid'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_notices_organization_id'), table_name='notices')
    op.drop_index('ix_notices_org_draft_status', table_name='notices')
    op.drop_index(op.f('ix_notices_draft_status'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_organizations_subscription_status'), table_name='organizations')
    op.drop_index('ix_organizations_plan_sub_status', table_name='organizations')
    op.drop_index(op.f('ix_organizations_plan'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_gstin'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_active_account_type', table_name='users')
    op.drop_index(op.f('ix_users_account_type'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
